apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rollouts-demo-gitops

helmCharts:
- name: argocd-app-of-app
  version: 0.2.6
  repo: https://gnunn-gitops.github.io/helm-charts
  valuesFile: values.yaml
  namespace: rollouts-demo-gitops
  releaseName: rollouts-demo