apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: rollouts-pipeline
spec:
  workspaces:
  - name: manifests
  params:
    - default: blue
      name: COLOR
      type: string
    - default: https://github.com/gitops-examples/rollouts-demo
      name: GIT_REPOSITORY
      type: string
    - default: main
      name: GIT_REF
      type: string
  tasks:
    - name: get-image-digest
      taskRef:
        name: image-tag-to-digest
      params:
        - name: image_dest_url
          value: argoproj/rollouts-demo
        - name: image_dest_tag
          value: $(params.COLOR)
    - name: dev-git-update
      taskRef:
        kind: Task
        name: git-update-deployment
      runAfter:
        - get-image-digest
      params:
      - name: GIT_REPOSITORY
        value: $(params.GIT_REPOSITORY)
      - name: GIT_REF
        value: $(params.GIT_REF)
      - name: NEW_IMAGE
        value: argoproj/rollouts-demo
      - name: NEW_DIGEST
        value: $(tasks.get-image-digest.results.image_digest)
      - name: KUSTOMIZATION_PATH
        value: environments/overlays/dev
      workspaces:
      - name: workspace
        workspace: manifests
    - name: dev-gitops-sync
      taskRef:
        name: argocd-task-sync-and-wait
      runAfter:
        - dev-git-update
      params:
        - name: application_name
          value: rollouts-demo-gitops/rollouts-demo-dev
    - name: prod-git-update
      taskRef:
        kind: Task
        name: git-update-deployment
      runAfter:
        - dev-gitops-sync
      params:
      - name: GIT_REPOSITORY
        value: $(params.GIT_REPOSITORY)
      - name: GIT_REF
        value: $(params.GIT_REF)
      - name: NEW_IMAGE
        value: argoproj/rollouts-demo
      - name: NEW_DIGEST
        value: $(tasks.get-image-digest.results.image_digest)
      - name: KUSTOMIZATION_PATH
        value: environments/overlays/prod
      workspaces:
      - name: workspace
        workspace: manifests
    - name: prod-gitops-sync
      taskRef:
        name: argocd-task-sync-and-wait
      runAfter:
        - prod-git-update
      params:
        - name: application_name
          value: rollouts-demo-gitops/rollouts-demo-prod
    # - name: smoke-test
    #   taskRef:
    #     name: siege
    #   runAfter:
    #     - prod-gitops-sync
    #   params:
    #     - name: URL
    #       value: http://rollout-bluegreen-preview-rollouts-demo-prod.apps.home.ocplab.com
    #     - name: CONCURRENT
    #       value: "20"
    #     - name: REPETITIONS
    #       value: "10"
    #     - name: THRESHOLD
    #       value: "5.0"
    # - name: promote
    #   when:
    #   - input: "$(tasks.smoke-test.results.FAILED)"
    #     operator: in
    #     values: ["false"]
    #   taskRef:
    #     name: argo-rollouts
    #   runAfter:
    #     - smoke-test
    #   params:
    #     - name: COMMAND
    #       value: promote
    #     - name: ROLLOUT
    #       value: rollout-bluegreen
    #     - name: NAMESPACE
    #       value: rollouts-demo-prod
    # - name: abort
    #   when:
    #   - input: "$(tasks.smoke-test.results.FAILED)"
    #     operator: in
    #     values: ["true"]
    #   taskRef:
    #     name: argo-rollouts
    #   runAfter:
    #     - smoke-test
    #   params:
    #     - name: COMMAND
    #       value: abort
    #     - name: ROLLOUT
    #       value: rollout-bluegreen
    #     - name: NAMESPACE
    #       value: rollouts-demo-prod
