apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: siege
spec:
  params:
  - name: URL
    type: string
  - name: CONCURRENT
    type: string
  - name: REPETITIONS
    type: string
  results:
  - description: Number of failed transactions
    name: FAILED_TRANSACTIONS
  - description: Number of successful transactions
    name: SUCCESSFUL_TRANSACTIONS
  - description: Number of transactions
    name: TRANSACTIONS
  steps:
  - image: quay.io/gnunn/tools:latest
    name: run-test
    script: |
      echo "Testing URL with command 'siege -r $(params.REPETITIONS) -c $(params.CONCURRENT) -v $(params.URL) -j' "
      RESULTS=$(siege -r $(params.REPETITIONS) -c $(params.CONCURRENT) -v $(params.URL) -j)

      echo $RESULTS | jq .failed_transactions > $(results.FAILED_TRANSACTIONS.path)
      echo $RESULTS | jq .successful_transactions > $(results.SUCCESSFUL_TRANSACTIONS.path)
      echo $RESULTS | jq .transactions > $(results.TRANSACTIONS.path)