apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  analysis:
    successfulRunHistoryLimit: 20
    unsuccessfulRunHistoryLimit: 10
  replicas: 8
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: canary
  template:
    metadata:
      labels:
        app: canary
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    canary:
      analysis:
        templates:
        - templateName: canary
        args:
        - name: query
          value: irate(haproxy_backend_http_responses_total{exported_namespace='rollouts-demo-prod', route=~"rollout-bluegreen-preview", code="5xx"}[1m]) > 5 or on() vector(0)
        - name: route-url
          value: canary-rollouts-demo-prod.apps.home.ocplab.com
      canaryService: canary-canary
      stableService: canary-stable
      trafficRouting:
        plugins:
          argoproj-labs/openshift:
            routes:
              - canary
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
