apiVersion: v1
kind: Service
metadata:
  name: canary-stable
spec:
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: canary
---
apiVersion: v1
kind: Service
metadata:
  name: canary-canary
spec:
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: canary