kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: smoke-tests
spec:
  args:
  - name: query
  - name: route-url
  - name: api-token
    valueFrom:
      secretKeyRef:
        name: monitor-auth-secret
        key: token
  metrics:
  - name: success-rate
    interval: 60s
    count: 2
    # NOTE: prometheus queries return results in the form of a vector.
    # So it is common to access the index 0 of the returned array to obtain the value
    successCondition: result[1] <= 5
    failureLimit: 1
    provider:
      web:
          url: https://thanos-querier-openshift-monitoring.apps.home.ocplab.com/api/v1/query?query={{ args.query }}
          headers:
            - key: Authorization
              value: "Bearer {{args.api-token}}"
          jsonPath: "{$.data.result[0]}"
      # prometheus:
      #   #address: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
      #   address: https://thanos-querier-openshift-monitoring.apps.home.ocplab.com
      #   query: |
      #     sum(irate(haproxy_backend_http_responses_total{exported_namespace='{{args.namespace}}', route=~"{{args.route-name}}", code!~"5.*"}[5m])) / sum(irate(haproxy_backend_http_responses_total{exported_namespace='{{args.namespace}}', route=~"{{args.route-name}}"}[5m])) > 0 or on() vector(0)
  - name: run-load
    provider:
      job:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: siege
                image: quay.io/gnunn/tools:latest
                command: [sh, -c]
                args: ["siege -c 20 -r 30 -v http://{{args.route-url}}"]
              restartPolicy: Never