apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: bluegreen
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  analysis:
    successfulRunHistoryLimit: 20
    unsuccessfulRunHistoryLimit: 10
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: bluegreen
  template:
    metadata:
      labels:
        app: bluegreen
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    blueGreen:
      activeService: bluegreen-active
      previewService: bluegreen-preview
      autoPromotionEnabled: false
      prePromotionAnalysis:
        templates:
        - templateName: smoke-tests
        args:
        - name: query
          value: irate(haproxy_backend_http_responses_total{exported_namespace='rollouts-demo-prod', route=~"rollout-bluegreen-preview", code="5xx"}[1m]) > 5 or on() vector(0)
        - name: route-url
          value: bluegreen-preview-rollouts-demo-prod.apps.home.ocplab.com
