apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rollouts-demo-prod

resources:
- monitor-token.yaml
- ../../../apps/rollout/overlays/bluegreen
- ../../../apps/rollout/overlays/canary
- networkpolicy-cicd.yaml
- rollouts-edit-cicd-rolebinding.yaml
