namespace: rollouts-demo-prod

resources:
- rollout-manager.yaml
- ../../../apps/rollout/base
- networkpolicy-cicd.yaml
- rollouts-edit-cicd-rolebinding.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:ea9ee912898e0685917241d0960e974064863d9ef8fcf8a1321faaec94fe0b92
  name: argoproj/rollouts-demo
