namespace: rollouts-demo-prod

resources:
- rollout-manager.yaml
- ../../../apps/rollout/base
- networkpolicy-cicd.yaml
- rollouts-edit-cicd-rolebinding.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:12a1c7e694f9dcbf5c44f1f642905dea45128227f450e695d900c241ff853c09
  name: argoproj/rollouts-demo
