apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rollouts-edit-cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-rollouts-aggregate-to-edit
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: rollouts-demo-cicd