apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rollouts-demo-dev

resources:
- ../../../apps/deploy/base

images:
- digest: sha256:ea9ee912898e0685917241d0960e974064863d9ef8fcf8a1321faaec94fe0b92
  name: argoproj/rollouts-demo
