apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rollouts-demo-dev

resources:
- ../../../apps/deploy/base

images:
- digest: sha256:3225193a6415b14b3fcdd160c40248b2bfd62f8c77326480559b91a41ced6e20
  name: argoproj/rollouts-demo
